const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      image: '/images/p1.jpg',
      price: 120, //679*829px
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Slim Pants',
      slug: 'adidas-slim-pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality pant',
    },
    {
      name: 'Puma Sneakers',
      slug: 'puma-sneakers',
      image: '/images/p5.jpg',
      price: 350,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 3,
      description: 'high quality product',
    },
    {
      name: 'Jordan Sneakers',
      slug: 'adidas-slim-shirt',
      image: '/images/p6.jpg',
      price: 400,
      countInStock: 2,
      brand: 'Jordan',
      rating: 4.9,
      numReviews: 2,
      description: 'high quality product',
    },
  ],
};
export default data;
